<a href="https://colab.research.google.com/github/dhruvalgupta2003/0xSCAN/blob/master/ML%20MODEL%20FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [2]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/latest_Scholarship_data.csv')

In [3]:
# printing the first 5 rows of the dataframe
movies_data.head()

_id  \
0  62fa0551b308357159b62aee   
1  62fa0a21b308357159b66e06   
2  62fa0af2b308357159b671d6   
3  62fa0bebb308357159b675fc   
4  62fa1086b308357159b6a381   

                                               title  \
0                        Virchow Scholarship Program   
1  Saksham Scholarship Program for Class 9-12 Stu...   
2  Saksham Scholarship Program for Graduate Stude...   
3  Saksham Scholarship Program for Postgraduate S...   
4              Santoor Scholarship Programme 2021-22   

                   deadline       award  \
0  2022-08-31T00:00:00.000Z  upto 20000   
1  2022-08-31T00:00:00.000Z        8000   
2  2022-08-31T00:00:00.000Z  upto 15000   
3  2022-08-31T00:00:00.000Z  upto 20000   
4  2023-01-20T00:00:00.000Z  upto 24000   

                                         description  \
0  Virchow Scholarship Program is an initiative o...   
1  ‘Saksham Scholarship Program for Drivers’ Chil...   
2  ‘Saksham Scholarship Program for Drivers’ Chil...   
3  ‘Saksham Scholarship Program for Drivers’ Chil...   
4  A future full of opportunities is now within y...   

                                             website  \
0  https://www.buddy4study.com/application/VISC2/...   
1  https://www.buddy4study.com/application/SKSP1/...   
2  https://www.buddy4study.com/application/SKSP2/...   
3  https://www.buddy4study.com/application/SKSP4/...   
4                                                NaN   

                                         elegibility origin  \
0                       Open for girl students only.  India   
1  Applicants must have secured 60% and above mar...  India   
2  Applicants must be studying in any year of the...  India   
3  Applicants must be studying in any year of the...  India   
4  Available only for young women from underprivi...  India   

                                        elegibility2  \
0  Students must be residents of Telangana or And...   
1  Annual family income of the applicants from al...   
2  Applicants must have secured 60% and above mar...   
3  Applicants must have secured 60% and above mar...   
4  Have passed Class 10 from a local government s...   

                                        elegibility3           state  \
0  Applicants must have scored at least 70% marks...  Andhra Pradesh   
1  Children or family members of Mahindra Finance...  Andhra Pradesh   
2  Annual family income of the applicants from al...  Andhra Pradesh   
3  Annual family income of the applicants from al...  Andhra Pradesh   
4  Have passed Class 12 from a government school/...  Andhra Pradesh   

        profession  gender  income                 createdAt  \
0  School Stundent  Female  600000  2022-08-15T08:35:29.463Z   
1   School Student     NaN  400000  2022-08-15T08:56:01.407Z   
2       Graduation     NaN  400000  2022-08-15T08:59:30.849Z   
3  Post Graduation     NaN  400000  2022-08-15T09:03:39.220Z   
4   School Student  Female     NaN  2022-08-15T09:23:18.757Z   

                  updatedAt  __v                       guu category userId  
0  2022-08-20T17:34:06.527Z    0  62fa2577557bf312e1c5af51      NaN    NaN  
1  2022-08-15T08:56:01.407Z    0                       NaN      NaN    NaN  
2  2022-08-15T09:00:01.600Z    0                       NaN      NaN    NaN  
3  2022-08-15T09:03:39.220Z    0                       NaN      NaN    NaN  
4  2022-08-15T09:23:18.757Z    0                       NaN      NaN    NaN

In [4]:
# number of rows and columns in the data frame

movies_data.shape

(193, 20)

In [5]:
# selecting the relevant features for recommendation

selected_features = ['title','description','elegibility','elegibility3','income']
print(selected_features)

['title', 'description', 'elegibility', 'elegibility3', 'income']


In [6]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [7]:
# combining all the 5 selected features

combined_features = movies_data['title']+' '+movies_data['description']+' '+movies_data['elegibility']+' '+movies_data['elegibility3']+' '+movies_data['income']

In [8]:
print(combined_features)

0      Virchow Scholarship Program Virchow Scholarshi...
1      Saksham Scholarship Program for Class 9-12 Stu...
2      Saksham Scholarship Program for Graduate Stude...
3      Saksham Scholarship Program for Postgraduate S...
4      Santoor Scholarship Programme 2021-22 A future...
                             ...                        
188    RGS-IBG Postgraduate Research Awards 2022 RGS-...
189    Faculty of Science Postgraduate Writing-Up Awa...
190    KTH India Scholarship 2022 KTH India Scholarsh...
191    test scholarship this is test scholarship Stud...
192     teasdfsdf sdsc Class 10 passed school students  
Length: 193, dtype: object


In [9]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 63)	0.09971983838095477
  (0, 506)	0.10449653041274526
  (0, 818)	0.07114231991656131
  (0, 65)	0.10449653041274526
  (0, 773)	0.08965876972130336
  (0, 1149)	0.08488207768951288
  (0, 874)	0.062841669903313
  (0, 149)	0.0636201689237996
  (0, 933)	0.06899989699558698
  (0, 935)	0.08488207768951288
  (0, 567)	0.07926581280474482
  (0, 1044)	0.11933429110418715
  (0, 543)	0.04438607567249529
  (0, 790)	0.0925171912861968
  (0, 1321)	0.09971983838095477
  (0, 1313)	0.11933429110418715
  (0, 1017)	0.11933429110418715
  (0, 1292)	0.07482100902986147
  (0, 209)	0.0776794305947549
  (0, 339)	0.07620254409034495
  (0, 679)	0.11065475750501923
  (0, 382)	0.08488207768951288
  (0, 1111)	0.08488207768951288
  (0, 1205)	0.062090492346353374
  (0, 362)	0.08488207768951288
  :	:
  (190, 707)	0.02544165459300622
  (190, 1139)	0.08333572631654658
  (191, 1288)	0.6884733528974146
  (191, 986)	0.22088711688384474
  (191, 989)	0.26112063097343463
  (191, 1091)	0.27290090165551734
  (191, 367)	0.23

Cosine Similarity

In [12]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.24925887 0.26038401 ... 0.10744835 0.08123135 0.0515903 ]
 [0.24925887 1.         0.8591068  ... 0.09935575 0.04547882 0.02485143]
 [0.26038401 0.8591068  1.         ... 0.12947817 0.04051894 0.01276808]
 ...
 [0.10744835 0.09935575 0.12947817 ... 1.         0.10564964 0.01366968]
 [0.08123135 0.04547882 0.04051894 ... 0.10564964 1.         0.00806816]
 [0.0515903  0.02485143 0.01276808 ... 0.01366968 0.00806816 1.        ]]


In [14]:
print(similarity.shape)

(193, 193)


Getting the movie name from the user

In [15]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : NEC Merit Scholarship


In [16]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Virchow Scholarship Program', 'Saksham Scholarship Program for Class 9-12 Students 2022-23', 'Saksham Scholarship Program for Graduate Students 2022-23', 'Saksham Scholarship Program for Postgraduate Students 2022-23', 'Santoor Scholarship Programme 2021-22', 'NEC Merit Scholarship for Students of NER 2022-23', 'Special Scholarship Scheme Ishan Uday for NER 2022-23', 'Umbrella Scheme for Education of ST Children Post Matric Scholarship, Arunachal Pradesh 2021-22', 'Scheme for Award of Stipend to ST Students, Arunachal Pradesh 2021', 'Tata AIG Avanti Fellows Scholarship Program 2022', 'Post-Matric Scholarship for SC Students 2022-23, Assam', ' NEC Merit Scholarship for Students of NER 2022-23', 'Special Scholarship Scheme Ishan Uday for Assam 2022-23 ', ' Tata AIG Avanti Fellows Scholarship Program Assam 2022', 'Post-Matric Scholarship for OBC Students 2022-23, Assam', 'Pre-Matric Scholarship for ST Students (Class 9 & 10) 2021-22, Assam', 'Vidyadhan Bihar Plus 2 (1st year) Program 20

In [17]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['test scholarship', 'NEC Merit Scholarship for Students of NER 2022-23']


In [18]:
close_match = find_close_match[0]
print(close_match)

test scholarship


In [19]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data['title'] == close_match].index.values[0]
print(index_of_the_movie)

191


In [20]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.081231353147531), (1, 0.04547881576902087), (2, 0.040518941733055966), (3, 0.05675387363664836), (4, 0.0910612601683836), (5, 0.2579441014248901), (6, 0.049933751488323644), (7, 0.037448996932743936), (8, 0.059310063895014094), (9, 0.043059698917702297), (10, 0.04649768122898686), (11, 0.19022091676785416), (12, 0.04446849960935559), (13, 0.04498556634092562), (14, 0.055020687305457144), (15, 0.052566903934865086), (16, 0.020184239324826884), (17, 0.009682353241661314), (18, 0.039855235451541994), (19, 0.06865453193763453), (20, 0.05449922461619033), (21, 0.04495000171221199), (22, 0.053818649767112946), (23, 0.05332318510487015), (24, 0.05048196794666374), (25, 0.027476642943501904), (26, 0.04200415521850366), (27, 0.05188654191015314), (28, 0.029904496818968316), (29, 0.039840562545365624), (30, 0.026568315218781807), (31, 0.027015002210274763), (32, 0.024089733998786618), (33, 0.05260034630745984), (34, 0.06385829912246097), (35, 0.019611881733209723), (36, 0.0370573158587834

In [21]:
len(similarity_score)

193

In [22]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(191, 1.0000000000000004), (141, 0.45697321313269484), (154, 0.39745712027140734), (115, 0.39708348194486165), (119, 0.3966755981120196), (112, 0.35664610913151773), (5, 0.2579441014248901), (11, 0.19022091676785416), (86, 0.17299573014338648), (66, 0.15747023448102515), (189, 0.1469260444965384), (121, 0.12811355398572344), (190, 0.10564964249810367), (184, 0.10536136039910997), (98, 0.10434632675429882), (164, 0.09873751991276819), (96, 0.09497342439832647), (163, 0.09458024766091412), (162, 0.09435888353502384), (146, 0.09229148178743127), (4, 0.0910612601683836), (94, 0.09088234043224827), (37, 0.08804450383286172), (118, 0.08619226978887545), (80, 0.08476936373727167), (171, 0.08426896200224678), (84, 0.08304634982334781), (81, 0.08234307769616239), (0, 0.081231353147531), (188, 0.07964134260608711), (52, 0.07951913690804154), (50, 0.07928478410113413), (44, 0.0792456272591538), (183, 0.07886894199211346), (101, 0.07806535192515196), (108, 0.07788504761425717), (124, 0.0775300856

In [23]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . test scholarship
2 . NEC Merit Scholarship for Students of NER 2022-23(Sikkim)
3 . NEC Merit Scholarship for Students of NER 2022-23(Tripura)
4 . NEC Merit Scholarship for Students of NER 2022-23(Meghalaya)
5 . NEC Merit Scholarship for Students of NER 2022-23(Mizoram)
6 . NEC Merit Scholarship for Students of NER 2022-23(Manipur)
7 . NEC Merit Scholarship for Students of NER 2022-23
8 .  NEC Merit Scholarship for Students of NER 2022-23
9 . Post-Matric Scholarship for Minorities of Karnataka 2022
10 . Mukhya Mantri Protsahan Yojana 2022, Himachal Pradesh
11 . Faculty of Science Postgraduate Writing-Up Award, University of Melbourne, 2022
12 . NEC Merit Scholarship for Students of NER 2022-23(Nagaland)
13 . KTH India Scholarship 2022
14 . Chevening India Cyber Security Fellowship 2022
15 . KSCSTE Kerala Research Fellowship 2021
16 . Postmatric (Other than Intermediate) Scholarship for ST, SC, General Category, Uttar Pradesh 2022-23
17 . APJ Abdul Kalaam

Movie Recommendation Sytem

In [24]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match].index.values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : NEC Merit Scholarship
Movies suggested for you : 

1 . test scholarship
2 . NEC Merit Scholarship for Students of NER 2022-23(Sikkim)
3 . NEC Merit Scholarship for Students of NER 2022-23(Tripura)
4 . NEC Merit Scholarship for Students of NER 2022-23(Meghalaya)
5 . NEC Merit Scholarship for Students of NER 2022-23(Mizoram)
6 . NEC Merit Scholarship for Students of NER 2022-23(Manipur)
7 . NEC Merit Scholarship for Students of NER 2022-23
8 .  NEC Merit Scholarship for Students of NER 2022-23
9 . Post-Matric Scholarship for Minorities of Karnataka 2022
10 . Mukhya Mantri Protsahan Yojana 2022, Himachal Pradesh
11 . Faculty of Science Postgraduate Writing-Up Award, University of Melbourne, 2022
12 . NEC Merit Scholarship for Students of NER 2022-23(Nagaland)
13 . KTH India Scholarship 2022
14 . Chevening India Cyber Security Fellowship 2022
15 . KSCSTE Kerala Research Fellowship 2021
16 . Postmatric (Other than Intermediate) Scholarship for ST, SC, Gene

In [25]:
#exporting pickle file for web
import pickle
pickle.dump(combined_features,open('combined_features.pkl','wb'))
pickle.dump(movies_data, open('scholarship_data.pkl','wb'))
pickle.dump(list_of_all_titles, open('list_of_all_titles.pkl','wb'))
pickle.dump(find_close_match, open('find_close_match.pkl','wb'))
pickle.dump(close_match, open('close_match.pkl','wb'))
pickle.dump(index_of_the_movie, open('index_of_the_scholarship.pkl','wb'))
pickle.dump(similarity_score, open('similarity_score.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))
pickle.dump(sorted_similar_movies, open('sorted_similar_scholarship.pkl','wb'))

