<a href="https://colab.research.google.com/github/dhruvalgupta2003/0xSCAN/blob/master/Scholarships_Recommendation_using_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [ ]:
# loading the data from the csv file to apandas dataframe
scholarship_data = pd.read_csv('/content/scholarships.csv')


In [ ]:
# printing the first 5 rows of the dataframe
scholarship_data.head()

index                       _id  \
0      1  62ecdb7511eecc8d7863e2b6   
1      2  62ecdcc611eecc8d7863e2b8   
2      3  62ecdd5511eecc8d7863e2ba   
3      4  62ecdec8eec8746e08200f6b   
4      5  62ecdf68eec8746e08200f6d   

                                               title    deadline  \
0  Vidyadhan Odisha Plus 2 (1st year) Scholarship...  22-08-2022   
1  SERB International Research Experience (SIRE) ...  30-08-2022   
2                           JSPN Scholarship 2022-23  30-08-2022   
3                        Virchow Scholarship Program  31-08-2022   
4     TISS Guwahati Summer Internship Programme 2022  31-08-2022   

                              award  \
0              INR 10,000 per annum   
1                   Variable Awards   
2                   Variable Awards   
3                  Up to INR 15,000   
4  INR 5,000 per month for 2 months   

                                         description  \
0  Vidyadhan Odisha Plus 2 (1st year) Scholarship...   
1  SERB International Research Experience (SIRE) ...   
2  JSPN Scholarship 2022-23 is an initiative of J...   
3  Virchow Scholarship Program is an initiative o...   
4  TISS Guwahati Summer Internship Programme 2022...   

                                             website  \
0                    https://www.vidyadhan.org/apply   
1                    https://serbonline.in/SERB/Sire   
2  https://www.srijspn.org/jspnapp/views/home.jsf...   
3  https://www.buddy4study.com/application/VISC2/...   
4  https://tiss.edu/uploads/files/ERB-SSR_Adverti...   

                                         elegibility origin  __v  \
0                           Class 10 passed students  India    0   
1                               Ph.D. degree holders  India    0   
2              Meritorious Madhwa community students  India    0   
3  Class 10 and 12 Girl Students from Telangana &...  India    0   
4  B.Tech./M.Tech./M.Sc. or final year postgradua...  India    0   

            state elegibility2 elegibility3 createdAt updatedAt  
0             NaN          NaN          NaN       NaN       NaN  
1             NaN          NaN          NaN       NaN       NaN  
2             NaN          NaN          NaN       NaN       NaN  
3  Andhra Pradesh          NaN          NaN       NaN       NaN  
4             NaN          NaN          NaN       NaN       NaN

In [ ]:
# number of rows and columns in the data frame

scholarship_data.shape

(119, 15)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['title','award','description','elegibility','state']
print(selected_features)

['title', 'award', 'description', 'elegibility', 'state']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  scholarship_data[feature] = scholarship_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = scholarship_data.filter(['title' , 'award', 'description', 'elegibility', 'state'],axis=1)

In [ ]:
print(combined_features)

                                                 title  \
0    Vidyadhan Odisha Plus 2 (1st year) Scholarship...   
1    SERB International Research Experience (SIRE) ...   
2                             JSPN Scholarship 2022-23   
3                          Virchow Scholarship Program   
4       TISS Guwahati Summer Internship Programme 2022   
..                                                 ...   
114    Mother Teresa Scholarship (MTS), Kerala 2021-22   
115  ITC Fee Reimbursement Scholarship, Kerala 2021-22   
116  APJ Abdul Kalaam Scholarship (APJAK), Kerala 2...   
117         Anandam Senapathi Scholarship, Kerala 2021   
118             KSCSTE Kerala Research Fellowship 2021   

                                                 award  \
0                                 INR 10,000 per annum   
1                                      Variable Awards   
2                                      Variable Awards   
3                                     Up to INR 15,000   
4            

In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 4)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (4, 3)	1.0


Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
print(similarity.shape)

(5, 5)


Getting the movie name from the user

In [ ]:
# getting the scholarships name from the user

scholarship_name = input(' Enter the scholarship you want to enroll into : ')
# scholarship_state = input(' Enter the State in which you want the scholarships : ')

 Enter the scholarship you want to enroll into : JSPN Scholarship


In [ ]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = scholarship_data['title'].tolist()
print(list_of_all_titles)

['Vidyadhan Odisha Plus 2 (1st year) Scholarship Program 2022', 'SERB International Research Experience (SIRE) 2022', 'JSPN Scholarship 2022-23', 'Virchow Scholarship Program', 'TISS Guwahati Summer Internship Programme 2022', 'BMU Kind Circle Scholarship 2022-23', 'Saksham Scholarship Program for Postgraduate Students 2022-23', 'HDFC Bank Parivartan’s ECS Scholarship 2022-23', 'Royal Global University Admission Scholarship 2022-23', 'Pre Matric Scholarship Scheme for OBC Students, Chandigarh 2022-23', 'Sharda University Admission Scholarship 2022-23', 'G. P. Birla Scholarship 2022', 'The Tata Capital Pankh Scholarship Programme for Professional Undergraduate Courses 2022-23', 'Mahindra All India Talent Scholarship (MAITS) 2022', 'TWAS-DBT Postgraduate Fellowship Programme 2022', 'Indian Institute of Astrophysics (IIA) Post-Doctoral Researcher Fellowship 2022', 'INSPIRE Awards MANAK Scheme 2022-23', 'Saksham Scholarship Program for Class 9-12 Students 2022-23', 'Saksham Scholarship Pro

In [ ]:
# finding the close match for the scholarship name given by the user

find_close_match = difflib.get_close_matches(scholarship_name, list_of_all_titles)
print(find_close_match)

['JSPN Scholarship 2022-23']


In [ ]:
close_match = find_close_match[0]
print(close_match)

JSPN Scholarship 2022-23


In [ ]:
# finding the index of the scholarship with title

index_of_the_scholarship = scholarship_data[scholarship_data.title == close_match]['index'].values[0]
print(index_of_the_scholarship)

3


In [ ]:
# getting a list of similar Scholarship

similarity_score = list(enumerate(similarity[index_of_the_scholarship]))
print(similarity_score)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 1.0), (4, 0.0)]


In [ ]:
len(similarity_score)

5

In [ ]:
# sorting the scholarship based on their similarity score

sorted_similar_scholarship = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_scholarship)

[(3, 1.0), (0, 0.0), (1, 0.0), (2, 0.0), (4, 0.0)]


In [ ]:
# print the name of similar scholarship based on the index

print('scholarship suggested for you : \n')

i = 1

for scholarship in sorted_similar_scholarship:
  index = scholarship[0]
  title_from_index = scholarship_data[scholarship_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

scholarship suggested for you : 

1 . Virchow Scholarship Program
2 . Vidyadhan Odisha Plus 2 (1st year) Scholarship Program 2022
3 . SERB International Research Experience (SIRE) 2022
4 . JSPN Scholarship 2022-23
5 . TISS Guwahati Summer Internship Programme 2022


Scholarship Recommendation Sytem

In [ ]:
scholarship_name = input(' Enter the Scholarship you want to enroll into : ')

list_of_all_titles = scholarship_data['title'].tolist()

find_close_match = difflib.get_close_matches(scholarship_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_scholarship = scholarship_data[scholarship_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_scholarship]))

sorted_similar_scholarship = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Scholarships suggested for you : \n')

i = 1

for scholarship in sorted_similar_scholarship:
  index = scholarship[0]
  title_from_index = scholarship_data[scholarship_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter the Scholarship you want to enroll into : JSPN Scholarship
Scholarships suggested for you : 

1 . Virchow Scholarship Program
2 . Vidyadhan Odisha Plus 2 (1st year) Scholarship Program 2022
3 . SERB International Research Experience (SIRE) 2022
4 . JSPN Scholarship 2022-23
5 . TISS Guwahati Summer Internship Programme 2022
